name: docker-build-and-push

on:
  workflow_dispatch:
    inputs:
      linkerd-version:
        description: 'A linkerd (stable) release version'
        required: true
        default: 2.17
      proxy-version:
        description: 'A linkerd proxy release'
        required: true
        default: 2.276.0

permissions:
  contents: read
  packages: write

env:
  DOCKER_REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    permissions:
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: version-${{ inputs.linkerd-version }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build images
        id: build-images
        run: |
          cd bin

          echo "v${{ inputs.proxy-version }}" > .proxy-version
          
          ./docker-build-proxy
          ./docker-build-controller
          ./docker-build-debug
          ./docker-build-policy-controller

          docker images

      - name: Tag images
        id: tag-images
        run: |
          docker tag ${DOCKER_REGISTRY}/proxy:version-${{ inputs.linkerd-version }} ${DOCKER_REGISTRY}/linkerd/proxy:${{ inputs.proxy-version }}
          docker tag ${DOCKER_REGISTRY}/controller:version-${{ inputs.linkerd-version }} ${DOCKER_REGISTRY}/linkerd/controller:${{ inputs.linkerd-version }}
          docker tag ${DOCKER_REGISTRY}/debug:version-${{ inputs.linkerd-version }} ${DOCKER_REGISTRY}/linkerd/debug:${{ inputs.linkerd-version }}
          docker tag ${DOCKER_REGISTRY}/policy-controller:version-${{ inputs.linkerd-version }} ${DOCKER_REGISTRY}/linkerd/policy-controller:${{ inputs.linkerd-version }}

          docker images





