name: docker-build-and-push

on:
  workflow_dispatch:
    inputs:
      linkerd-version:
        description: 'A linkerd (stable) release version'
        required: true
        default: 2.17
      proxy-version:
        description: 'A linkerd proxy release'
        required: true
        default: 2.276.0

env:
  DOCKER_REGISTRY: 'ghcr.io'

jobs:
  build-and-push:
    runs-on: ubuntu-24.04

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          ref: version-${{ inputs.linkerd-version }}

      - name: Build and tag images
        id: build-and-tag
        run: |
          cd bin

          echo "v${{ inputs.proxy-version }}" > .proxy-version
          
          ./docker-build-proxy
          ./docker-build-controller
          #./docker-build-debug
          #./docker-build-policy-controller


          #echo PROXY_IMAGE="${DOCKER_REGISTRY}/linkerd/proxy:${{ inputs.proxy-version }}"
          #echo CONTROLLER_IMAGE="${DOCKER_REGISTRY}/linkerd/controller:${{ inputs.linkerd-version }}"
          #echo DEBUG_IMAGE="${DOCKER_REGISTRY}/linkerd/debug:${{ inputs.linkerd-version }}"
          #echo POLICY_CONTROLLER_IMAGE="${DOCKER_REGISTRY}/linkerd/policy-controller:${{ inputs.linkerd-version }}"


          #docker tag cr.l5d.io/linkerd/proxy:"$INTERNAL_LINKERD_VERSION" "$PROXY_IMAGE"
          #docker tag cr.l5d.io/linkerd/controller:"$INTERNAL_LINKERD_VERSION" "$CONTROLLER_IMAGE"
          #docker tag cr.l5d.io/linkerd/debug:"$INTERNAL_LINKERD_VERSION" "$DEBUG_IMAGE"
          #docker tag cr.l5d.io/linkerd/policy-controller:"$INTERNAL_LINKERD_VERSION" "$POLICY_CONTROLLER_IMAGE"




          docker images











